In [59]:
import numpy as np
import math
a = np.array([[1.1, '2', 3],
              [4, 5, 6]],dtype=float)
a.shape

# Array attributes
a.ndim

2

In [56]:
a[0]

array(['1.1', '2', '3'], dtype='<U32')

In [51]:
len(a.shape) == a.ndim

True

In [24]:
a.size

6

In [52]:
a.size == math.prod(a.shape)

True

In [53]:
a.shape

(2, 3)

In [54]:
a.dtype


dtype('float64')

In [39]:
data = [
    ['101', 'Apple', '1.99', '100'],   # product_id, name, price, quantity_sold
    ['102', 'Banana', '0.5', '250'],
    ['103', 'Grapes', 'free', '300'],  # oops! someone wrote 'free' instead of price
]

In [62]:
arr = np.array(data)  # default dtype=object or str
# print(arr.dtype)
arr

array([['101', 'Apple', '1.99', '100'],
       ['102', 'Banana', '0.5', '250'],
       ['103', 'Grapes', 'free', '300']], dtype='<U6')

In [63]:
# This will fail
arr[:, 2].astype(float) * arr[:, 3].astype(int)

ValueError: could not convert string to float: np.str_('free')

In [32]:
arr[:, 2]

array(['1.99', '0.5', 'free'], dtype='<U6')

In [64]:
def parse_row(row):
    try:
        return (int(row[0]), row[1], float(row[2]), int(row[3]))
    except ValueError:

        print('isnide alue:',row)
        return None  # drop or log the bad row

In [65]:
cleaned = [parse_row(row) for row in data if parse_row(row)]
cleaned

isnide alue: ['103', 'Grapes', 'free', '300']


[(101, 'Apple', 1.99, 100), (102, 'Banana', 0.5, 250)]

In [66]:
arr = np.array(cleaned, dtype=[('id', 'i4'), ('name', 'U10'), ('price', 'f4'), ('qty', 'i4')])
arr

array([(101, 'Apple', 1.99, 100), (102, 'Banana', 0.5 , 250)],
      dtype=[('id', '<i4'), ('name', '<U10'), ('price', '<f4'), ('qty', '<i4')])

In [68]:
# Total revenue per product
revenue = arr['price'] * arr['qty']
print("Revenue:", revenue)

# Best-selling item
best_idx = np.argmax(revenue)
print("Top product:", arr[best_idx]['name'])


Revenue: [199.00000095 125.        ]
Top product: Apple


In [ ]:
# # Case Study: Inventory Optimization for a Retail Store
# 🧩 Problem:
# A retail chain has inventory data for 5 stores and 4 products. You want to:

# Calculate the total inventory across stores.

# Apply a restocking threshold (broadcasting).

# Calculate cost of inventory per product (vectorized multiplication).

In [71]:
inventory = np.array([
    [20, 35, 10, 50],
    [30, 40, 20, 60],
    [15, 30, 25, 40],
    [50, 20, 30, 70],
    [10, 45, 15, 55]
])

# Unit prices for 4 products
prices = np.array([100, 150, 200, 250])

In [74]:
#  Step 2: Total Inventory for Each Product
inventory.sum(axis=1)

array([115, 150, 110, 170, 125])

In [75]:
# 🚨 Step 3: Find Low Stock (Broadcasting threshold)

In [81]:
threshold = 20

In [83]:
low_stock_mask = inventory < threshold
low_stock_mask
print("Low Stock (less than 20):\n", low_stock_mask)

Low Stock (less than 20):
 [[False False  True False]
 [False False False False]
 [ True False False False]
 [False False False False]
 [ True False  True False]]


In [86]:
# 💰 Step 4: Compute Total Inventory Cost per Store
inventory_value = inventory * prices 
store_inventory_cost = inventory_value.sum(axis=1)
print("Total Inventory Cost per Store:", store_inventory_cost)

Total Inventory Cost per Store: [21750 28000 21000 31500 24500]


In [89]:
discount_mask = inventory > 40
discounted_inventory_value = np.where(discount_mask, inventory * prices * 0.9, inventory * prices)
print("Discounted Inventory Value:\n", discounted_inventory_value)


Discounted Inventory Value:
 [[ 2000.  5250.  2000. 11250.]
 [ 3000.  6000.  4000. 13500.]
 [ 1500.  4500.  5000. 10000.]
 [ 4500.  3000.  6000. 15750.]
 [ 1000.  6075.  3000. 12375.]]


In [91]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])
b.shape

(2, 3)

In [92]:
# Add arrays
print("a + b:\n", a + b)

a + b:
 [[11 22 33]
 [44 55 66]]


In [93]:
# Multiply arrays
print("a * b:\n", a * b)

a * b:
 [[ 10  40  90]
 [160 250 360]]


In [102]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([10, 20, 30])  # shape (3,)

# Broadcasting adds y to every row of x
result = x + y.T
result

array([[11, 22, 33],
       [14, 25, 36]])

In [105]:
y.T.shape

(3,)

In [ ]:
#  Case 1: Salary Increment Calculation (Beginner - Broadcasting)
# You have salaries of 4 employees:

salaries = np.array([25000, 30000, 28000, 35000])
# 💼 The company wants to give a flat increment of ₹2000 to each employee.

# ❓ Question:
# What will be the new salaries using NumPy without writing a loop?

In [ ]:
#  Case 2: Student Scores (Vectorized Average)
scores = np.array([
    [80, 70, 90],   # Student 1
    [60, 75, 85],   # Student 2
    [78, 82, 88]    # Student 3
])

Using NumPy, calculate the average score for each student.

In [106]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'